/// Number (int & double) utility extensions.
extension IntX on int {
  /// Duration in milliseconds.
  Duration get ms => Duration(milliseconds: this);

  /// Duration in seconds.
  Duration get seconds => Duration(seconds: this);

  /// Duration in minutes.
  Duration get minutes => Duration(minutes: this);

  /// Duration in hours.
  Duration get hours => Duration(hours: this);

  /// Duration in days.
  Duration get days => Duration(days: this);

  /// Whether this integer is even.
  bool get isEven => this % 2 == 0;

  /// Whether this integer is odd.
  bool get isOdd => this % 2 != 0;

  /// Whether this integer is in [min]..[max] (inclusive).
  bool between(int min, int max) => this >= min && this <= max;

  /// Returns the value clamped between [min] and [max].
  int clampTo(int min, int max) => clamp(min, max).toInt();

  /// Repeats [action] this many times, passing the index (0-based).
  void times(void Function(int index) action) {
    for (int i = 0; i < this; i++) {
      action(i);
    }
  }

  /// Returns a list generated by [generator] with [this] items.
  List<T> generate<T>(T Function(int index) generator) =>
      List<T>.generate(this, generator);
}

/// Double utility extensions.
extension DoubleX on double {
  /// Duration in milliseconds (fractional seconds support).
  Duration get ms => Duration(microseconds: (this * 1000).round());

  /// Duration in seconds (fractional support).
  Duration get seconds => Duration(microseconds: (this * 1e6).round());

  /// Whether this double is in [min]..[max] (inclusive).
  bool between(double min, double max) => this >= min && this <= max;

  /// Returns the value clamped between [min] and [max].
  double clampTo(double min, double max) => clamp(min, max).toDouble();

  /// Rounds to [fractionDigits] decimal places.
  double toPrecision(int fractionDigits) {
    final double mod = _pow10(fractionDigits);
    return (this * mod).round() / mod;
  }

  double _pow10(int n) {
    double result = 1;
    for (int i = 0; i < n; i++) {
      result *= 10;
    }
    return result;
  }
}

/// Num utility extensions (shared between int and double).
extension NumX on num {
  /// Whether this value is between [min] and [max] (inclusive).
  bool isBetween(num min, num max) => this >= min && this <= max;
}
