name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze lib

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test --exclude-tags golden

  publish:
    name: Publish dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: git reset --hard
      - run: flutter pub publish --dry-run

  example:
    name: Example analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
        working-directory: example
      - run: flutter analyze
        working-directory: example
      - run: flutter test
        working-directory: example

  integration:
    name: Integration test & Goldens (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Run Golden Tests
        run: flutter test test/golden_test.dart
      - run: flutter pub get
        working-directory: example
      - run: flutter test integration_test/app_test.dart -d windows
        working-directory: example
